### Get tasks
GET https://localhost:8081/signup

### Add new task 
POST https://todo-backend-4kqy.onrender.com/new HTTP/1.1
Content-Type: application/json

### Delete task
DELETE https://todo-backend-4kqy.onrender.com/delete/7 HTTP/1.1

{
    "description": "Test from REST Client"
}