### Get tasks
# https://localhost:PORT/api/ENDPOINTS

### Signup a new user
POST http://localhost:8081/api/signup HTTP/1.1
Content-Type: application/json

{
    "firstName" : "Maria",
    "lastName" : "Dave",
    "username" : "maria-dave",
    "password" : "12345",
    "bio" : "Hey everybody!I am John`s friend"
}

### Login a new user
POST http://localhost:8081/api/login  HTTP/1.1
Content-Type: application/json

{ 
    "username" : "john-dave",
    "password" : "1234"
}

### Get Info of  user
GET   http://localhost:8081/user/getInfo/642563d03d296424b95ac5dc  HTTP/1.1



### Get username of user
GET   http://localhost:8081/users/getUserUserName/642563d03d296424b95ac5dc HTTP/1.1

### 
POST http://localhost:8081/user/getUserUsername  HTTP/1.1
Content-Type: application/json

{ 
    "userId" : "642563d03d296424b95ac5dc"

}
### Post a picture
POST http://localhost:8081/api/picture HTTP/1.1
Content-Type: application/json

{
    "userId" : "642563d03d296424b95ac5dc",
    "description" : "My first pic",
    "pictureImage" : "mupic"
}

// with deployment link will be https
// test endpoints of API
// create a documentation for api
